name: compile-wasm-to-pkg

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: build wasm to pkg
      run: wasm-pack build --target web --release

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: commit pkg to release branch
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto deploy($SHORT_SHA)
        branch: release
        create_branch: true,
        add_options: '-f'
